### ISSUE TITLE
Obtain first results for paper

### ISSUE THREAD

**Issue by gomezzz** [rasmusmarak/TOSS#18]

**Comment by gomezzz** [comment]
# Two first scenarios

## Baseline
* 2 Satellites 
* Fixed initial position to the same
* 1 Maneuver
* Duration can be short

## More complex
* Let's leave initial position open for now  (to be discussed)
* Multiple spacecraft - 4 spacecraft
* Try to increase duration a bit to have a more comprehensive mission
* Two maneuvers

**Comment by gomezzz** [comment]
@rasmusmarak please post results here incl trajectory plots and whatever else you have 

also post parameters (ranges)

**Comment by rasmusmarak** [comment]
**Updated fitness over generations:**

_Fitness:_ Covered space + close distance penalty + far distance penalty
_Start time:_ 0 [s]
_End time:_ 10 [s]
_Delta t:_ 1 [s]
_V_max scaling:_ 40
_Penalty scaling:_ 0.1

_Number of spacecrafts:_ 1
_Number o maneuvers:_ 0

_Number of generations:_ 1000
_Population size:_ 120
_Number of threads:_ 40

![Skärmavbild 2023-05-03 kl  11 22 10](https://user-images.githubusercontent.com/60341145/235878728-1e535c7d-68f3-45a6-8f3a-2b25cb5afdaa.png)

**Comment by rasmusmarak** [comment]
Profile code for initial test with 1 spacecraft and 1 maneuver, and a mission duration of 4 weeks, can be found in #29

**Comment by rasmusmarak** [comment]
**_Case 1: (without rotation)_**

**Optimization settings:**
_Fitness function:_ CoveredSpace+CloseDistancePenalty+FarDistancePenalty
_Number of spacecrafts:_ 1
_Number of maneuvers:_ 1
_Start time:_ 0 [s]
_End time:_ 2419200 [s] (i.e 4 weeks, or 28 days)
_Rotation:_ False

_Measurement period:_ 100 [s]
_Penalty scaling:_ 0.1
_Max velocity scaling:_ 40
_Max velocity:_ [-0.02826052, 0.1784372, -0.29885126] [m/s] (in xyz-coordinates)

_Radius inner bounding sphere:_ 4000 [m]
_Radius outer bounding sphere:_ 15000 [m]

_Population size:_ 120
_Number of generations:_ 1000
_Number of threads:_ 40

**Bounds for initial state:**
a = [4000, 15000]
e = [0, 1]        
o = [0, 2*pi]
w = [0, 2*pi]     
i = [0, pi]       
ea = [0, 2*pi]

_Impulsive maneuvers:_
tm = [(start_time + 1), (final_time - 1)]    (time for maneuver)
dvx = [-0.5, 0.5]
dvy = [-0.5, 0.5]
dvz = [-0.5, 0.5]


**Results:**

_Optimization run time:_ 7.057814452862739563e+04 [s]
_Champion fitness:_ -3.670855659772738200e-01
_Champion chromosome:_ 
[champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11415572/champion_x.csv)

**_Fitness over Generations:_**
![Skärmavbild 2023-05-07 kl  18 52 40](https://user-images.githubusercontent.com/60341145/236691339-1fdc5b4f-2742-4b79-bbc1-b08eeece154b.png)
[Fitness_over_generations.csv](https://github.com/rasmusmarak/TOSS/files/11415580/Fitness_over_generations.csv)

**_Trajectory plot:_**
![Skärmavbild 2023-05-07 kl  18 54 43](https://user-images.githubusercontent.com/60341145/236691419-763ed291-708f-460a-9f43-041e74ec7ed7.png)

_Close-up risky positions: (radius < 3000 [m])_
![Skärmavbild 2023-05-07 kl  19 00 30](https://user-images.githubusercontent.com/60341145/236691668-8cb8b435-8587-44a1-8d55-66ee7e3b6993.png)

**Comment by rasmusmarak** [comment]
**_Case 1: (with rotation)_**

**Optimization settings:**
_Fitness function:_ CoveredSpace+CloseDistancePenalty+FarDistancePenalty
_Number of spacecrafts:_ 1
_Number of maneuvers:_ 1
_Start time:_ 0 [s]
_End time:_ 2419200 [s] (i.e 4 weeks, or 28 days)
_Rotation:_ True

_Measurement period:_ 100 [s]
_Penalty scaling:_ 0.1
_Max velocity scaling:_ 40
_Max velocity:_ [-0.02826052, 0.1784372, -0.29885126] [m/s] (in xyz-coordinates)

_Radius inner bounding sphere:_ 4000 [m]
_Radius outer bounding sphere:_ 15000 [m]

_Population size:_ 120
_Number of generations:_ 1000
_Number of threads:_ 40

**Bounds for initial state:**
a = [4000, 15000]
e = [0, 1]        
o = [0, 2*pi]
w = [0, 2*pi]     
i = [0, pi]       
ea = [0, 2*pi]

_Impulsive maneuvers:_
tm = [(start_time + 1), (final_time - 1)]    (time for maneuver)
dvx = [-0.5, 0.5]
dvy = [-0.5, 0.5]
dvz = [-0.5, 0.5]


**Results:**
_Collisions:_ 0
_Optimization run time:_ 4.026962128949165344e+04 [s]
_Champion fitness:_ 1.353038492045705865e-01
_Champion chromosome:_ 
[champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11415787/champion_x.csv)

**_Fitness over Generations:_**
[Fitness_over_generations.csv](https://github.com/rasmusmarak/TOSS/files/11415790/Fitness_over_generations.csv)
![Skärmavbild 2023-05-07 kl  21 07 16](https://user-images.githubusercontent.com/60341145/236697665-ba3d1f02-18a1-4d99-806c-3bbbdf63f472.png)


**_Fitness sensitivity:_**
![Skärmavbild 2023-05-07 kl  21 08 16](https://user-images.githubusercontent.com/60341145/236697722-1c324797-fb2a-41fd-a5cd-708375df58e5.png)

**_Trajectory plot:_**
![Skärmavbild 2023-05-07 kl  21 09 28](https://user-images.githubusercontent.com/60341145/236697768-3a0fa657-31e1-4398-89cc-fcce5482d4c7.png)
![Skärmavbild 2023-05-07 kl  21 09 58](https://user-images.githubusercontent.com/60341145/236697792-92c2cc5a-3a0f-4064-9504-b5b83e472861.png)

**Comment by rasmusmarak** [comment]
**Cases to run:**

_**Case 1:**_
1 spacecraft 
2 maneuvers
4 weeks (or similar, find reference for a good long duration)
with and without rotation (to compare difficulty)

_**Case 2:**_
4 spacecraft
4 maneuvers
4 weeks (or similar, find reference for a good long duration)


outer_bounding sphere = 10000 (10 km)

**Comment by rasmusmarak** [comment]
1 spacecraft
2 maneuvers
4 weeks duration

[1S_2M_1000Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11528419/1S_2M_1000Gen_champion_f.csv)
[1S_2M_1000Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11528422/1S_2M_1000Gen_champion_x.csv)
[1S_2M_1000Gen_fitness_list.csv](https://gith
[1S_2M_1000Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11528425/1S_2M_1000Gen_run_time.csv)
ub.com/rasmusmarak/TOSS/files/11528424/1S_2M_1000Gen_fitness_list.csv)
![coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/ccd7277b-f59b-48b7-8d85-ff2795ce0f9b)

![distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/0244ccf8-2d09-4469-be75-a7926fd4d5a6)
![fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/4862ccf5-4d93-48f4-930e-a49726d4684c)
![fixed_body_frame_trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/4fafcbe8-c35c-448e-bcb3-80fc8e926d07)

![trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/5566c8ca-d002-42cd-a899-3fb57ded82ce)

**Comment by rasmusmarak** [comment]
**Test 1**
_Far distance penalty function:_  (mean(d__ - r_s)/ r_s**2)**(1/4) * 0.1
[T1_1S_2M_50Gen_champion_f..csv](https://github.com/rasmusmarak/TOSS/files/11541800/T1_1S_2M_50Gen_champion_f.csv)
[T1_1S_2M_50Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11541801/T1_1S_2M_50Gen_champion_x.csv)
[T1_1S_2M_50Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11541802/T1_1S_2M_50Gen_fitness_list.csv)
[T5_1S_2M_100Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11541808/T5_1S_2M_100Gen_run_time.csv)
![trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/936cc83f-a4db-4a81-832b-354cb394e05c)
![coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/a8490119-2fbe-4435-ac11-e8cae15abc03)
![fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/18325114-36c9-4670-8ccf-afe7956f2cb7)
![distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/492c4526-255a-4e1e-9d9b-1588726f58d6)


**Test 2**
_Far distance penalty function:_ (mean(d - r_s)/ r_s**2)**(1/4)
[T2_1S_2M_200Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11541821/T2_1S_2M_200Gen_champion_f.csv)
[T2_1S_2M_200Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11541822/T2_1S_2M_200Gen_champion_x.csv)
[T2_1S_2M_200Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11541823/T2_1S_2M_200Gen_fitness_list.csv)
[T2_1S_2M_200Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11541826/T2_1S_2M_200Gen_run_time.csv)
![trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/e63b79d2-6dc9-4c31-b047-c35ec2056b77)
![coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/9fda6ceb-2d5e-49d4-bea8-c0d2583197dd)
![distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/0b227791-46e0-4c55-aa54-bad65fb923dd)
![fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/6169a67a-29f0-493e-b1ca-ede71d1e5c17)


**Test 3**
_Far distance penalty function:_ (mean(d - r_s)/ r_s**2)**(1/2)
[T3_1S_2M_100Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11541829/T3_1S_2M_100Gen_champion_f.csv)
[T3_1S_2M_100Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11541831/T3_1S_2M_100Gen_champion_x.csv)
[T3_1S_2M_100Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11541835/T3_1S_2M_100Gen_fitness_list.csv)
[T3_1S_2M_100Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11541837/T3_1S_2M_100Gen_run_time.csv)
![trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/6987cf14-c086-4bc2-8d69-da8638910510)
![coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/aae5ef95-aed1-44a6-a2fd-71fa587e4b0f)
![distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/c0839084-1639-4128-883d-441303323c1c)
![fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/478ab477-d99a-4876-98ae-e852198bffb0)

**Test 5**
_Far distance penalty function:_ (mean(d - r_s)/ r_s**2)
[T5_1S_2M_100Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11541850/T5_1S_2M_100Gen_champion_f.csv)
[T5_1S_2M_100Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11541852/T5_1S_2M_100Gen_champion_x.csv)
[T5_1S_2M_100Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11541853/T5_1S_2M_100Gen_fitness_list.csv)
[T5_1S_2M_100Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11541855/T5_1S_2M_100Gen_run_time.csv)
![trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/50c2f502-09f1-497a-abca-18c62e743224)
![coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/5ad9e5ac-ac30-438d-be4c-481ca2e12052)
![distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/c5e27780-620c-45e2-ab71-eca84d1d7631)
![fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/6ce87dd5-5e85-45dd-bedf-35503fdf6805)

**Comment by rasmusmarak** [comment]
**Test 9:**

**_No changes:_**
_Info:_
dv_magnitude = [-2.5, 2.5]
v_magnitude = [-0.5, 0.5]
penalty = ((mean_distance/(radius_outer_bounding_sphere**2))**(1/4)) * 0.1
[T9_1S_2M_1000Gen_info.txt](https://github.com/rasmusmarak/TOSS/files/11551260/T9_1S_2M_1000Gen_info.txt)
[T9_1S_2M_1000Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11551262/T9_1S_2M_1000Gen_champion_f.csv)
[T9_1S_2M_1000Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11551263/T9_1S_2M_1000Gen_champion_x.csv)
[T9_1S_2M_1000Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11551264/T9_1S_2M_1000Gen_fitness_list.csv)
[T9_1S_2M_1000Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11551266/T9_1S_2M_1000Gen_run_time.csv)
![T9_1S_2M_1000Gen_trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/88dfde9c-9c58-4efd-b616-36ba7c8edf73)
![T10_1S_2M_1000Gen_fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/c47e0cc0-a6d7-47b7-8f99-b9b1e3f0d1e2)
![T10_1S_2M_1000Gen_coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/890e86b1-7ac8-449c-a867-e954edf7eeb9)
![T10_1S_2M_1000Gen_distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/4db6bf32-4a8d-4011-a7ee-9c978c89cd58)

**Comment by rasmusmarak** [comment]
**Test 10:**

**_Change:_** Increased velocity magnitude range
_info:_
dv_magnitude = [-2.5, 2.5]
v_magnitude = [-1.5, 1.5]
penalty = ((mean_distance/(radius_outer_bounding_sphere**2))**(1/4)) * 0.1

[T10_1S_2M_1000Gen_info.txt](https://github.com/rasmusmarak/TOSS/files/11551289/T10_1S_2M_1000Gen_info.txt)
[T10_1S_2M_1000Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11551291/T10_1S_2M_1000Gen_champion_f.csv)
[T10_1S_2M_1000Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11551292/T10_1S_2M_1000Gen_champion_x.csv)
[T10_1S_2M_1000Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11551293/T10_1S_2M_1000Gen_fitness_list.csv)
[T10_1S_2M_1000Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11551295/T10_1S_2M_1000Gen_run_time.csv)
![T10_1S_2M_1000Gen_trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/62053f6a-af72-4e74-bdee-4d99bd1b2e02)
![T10_1S_2M_1000Gen_fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/23445615-9d98-4af0-929f-a6e8489b5351)
![T10_1S_2M_1000Gen_coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/6125f927-6908-4197-a5ee-5e6dd471aaf8)
![T10_1S_2M_1000Gen_distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/c46ac7d5-7f32-46f9-8459-d2a0a8fd3271)

**Comment by rasmusmarak** [comment]
**Test 11:**

_**Change: **_ Increased penalty scaling: 0.1 -> 0.5
_info:_
dv_magnitude = [-2.5, 2.5]
v_magnitude = [-0.5, 0.5]
penalty = ((mean_distance/(radius_outer_bounding_sphere**2))**(1/4)) * 0.5

[T11_1S_2M_1000Gen_info.txt](https://github.com/rasmusmarak/TOSS/files/11551307/T11_1S_2M_1000Gen_info.txt)
[T11_1S_2M_1000Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11551311/T11_1S_2M_1000Gen_champion_f.csv)
[T11_1S_2M_1000Gen_champion_x.csv](https://github.co
[T11_1S_2M_1000Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11551314/T11_1S_2M_1000Gen_fitness_list.csv)
m/rasmusmarak/TOSS/files/11551313/T11_1S_2M_1000Gen_champion_x.csv)
[T11_1S_2M_1000Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11551315/T11_1S_2M_1000Gen_run_time.csv)
![T11_1S_2M_1000Gen_trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/724846d2-a32a-41c1-af5b-0c1adb40e93d)
![T11_1S_2M_1000Gen_fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/02848296-ddd1-494b-baa9-a2994cc56b1e)
![T11_1S_2M_1000Gen_coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/b3c97522-d300-491f-bbf3-83128f7d24c7)
![T11_1S_2M_1000Gen_distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/84bb48ff-c2e4-4726-af89-bea74292af99)

**Comment by rasmusmarak** [comment]
**Test 12:**

**_Change:_** Added maneuvers:  2 -> 4
_info:_
dv_magnitude = [-2.5, 2.5]
v_magnitude = [-0.5, 0.5]
penalty = ((mean_distance/(radius_outer_bounding_sphere**2))**(1/4)) * 0.1

[T7_1S_4M_1000Gen_info.txt](https://github.com/rasmusmarak/TOSS/files/11551352/T7_1S_4M_1000Gen_info.txt)
[T7_1S_4M_1000Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11551353/T7_1S_4M_1000Gen_champion_f.csv)
[T7_1S_4M_1000Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11551354/T7_1S_4M_1000Gen_champion_x.csv)
[T7_1S_4M_1000Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11551355/T7_1S_4M_1000Gen_fitness_list.csv)
[T7_1S_4M_1000Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11551357/T7_1S_4M_1000Gen_run_time.csv)
![T7_1S_4M_1000Gen_trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/f71b0c54-aeca-423e-aaed-3718f2223261)
![T7_1S_4M_1000Gen_fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/98ec98f2-498b-4140-ba19-a5b758c39cbc)
![T7_1S_4M_1000Gen_coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/7305e8fa-a037-4ca0-837a-bcf8bbfff067)
![T7_1S_4M_1000Gen_distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/8495e398-9fce-41d2-84e3-e4d0501ccb42)

**Comment by rasmusmarak** [comment]
_**Test 15:**_

_**Change: **_number of maneuvers = 4, dv_magnitude = [0, 2.5], v_magnitude = [0, 0.5], radius_outer_bounding_sphere = 12500

_Info:_
initial_position = [-135.13402075, -4089.53592604, 6050.17636635]
number of spacecraft = 1
number of maneuvers = 4
radius_outer_bounding_sphere = 12500
dv_magnitude = [0, 2.5]
v_magnitude = [0, 0.5]
penalty = ((mean_distance/(radius_outer_bounding_sphere**2))**(1/4)) * 0.1



[T15_1
[T15_1S_4M_1000Gen_info.txt](https://github.com/rasmusmarak/TOSS/files/11564720/T15_1S_4M_1000Gen_info.txt)
S_4M_1000Gen_champion_f.csv](https://github.com/rasmusmarak/TOSS/files/11564719/T15_1S_4M_1000Gen_champion_f.csv)
[T15_1S_4M_1000Gen_champion_x.csv](https://github.com/rasmusmarak/TOSS/files/11564722/T15_1S_4M_1000Gen_champion_x.csv)
[T15_1S_4M_1000Gen_fitness_list.csv](https://github.com/rasmusmarak/TOSS/files/11564724/T15_1S_4M_1000Gen_fitness_list.csv)
[T15_1S_4M_1000Gen_run_time.csv](https://github.com/rasmusmarak/TOSS/files/11564725/T15_1S_4M_1000Gen_run_time.csv)
![T15_1S_4M_1000Gen_trajectory_plot](https://github.com/rasmusmarak/TOSS/assets/60341145/172b23d2-42c5-4279-b179-476b3ec24294)
![T15_1S_4M_1000Gen_coverage_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/60c2a4ab-de8d-4eb2-bc83-5969d725a979)
![T15_1S_4M_1000Gen_distance_deviation_over_time](https://github.com/rasmusmarak/TOSS/assets/60341145/769cf670-f8a3-48cd-8ad8-7a02c508f4f1)
![T15_1S_4M_1000Gen_fitness_over_generations](https://github.com/rasmusmarak/TOSS/assets/60341145/9177468c-2ce6-457f-88cc-26e8761c808b)

**Comment by rasmusmarak** [comment]
**New results with rotating spherical grid: **

**_Case 1:_**
1 Spacecraft 
4 Maneuvers
Convergence (1e-6) = 280 generations
Tot Dv = 2.778971735322927 [m/s]

[Inertial_frame_side_view_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593505/Inertial_frame_side_view_trajectory_plot.pdf)
[Inertial_frame_top_view_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593507/Inertial_frame_top_view_trajectory_plot.pdf)
[body_fixed_frame_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593509/body_fixed_frame_trajectory_plot.pdf)
[case_1_fitness_over_generations.pdf](https://github.com/rasmusmarak/TOSS/files/11593510/case_1_fitness_over_generations.pdf)
[case_1_coverage_over_time.pdf](https://github.com/rasmusmarak/TOSS/files/11593511/case_1_coverage_over_time.pdf)
[case_1_distance_deviation_over_time.pdf](https://github.com/rasmusmarak/TOSS/files/11593512/case_1_distance_deviation_over_time.pdf)

**Comment by rasmusmarak** [comment]
**New results with rotating spherical grid:**

**_Case 2:_**
4 Spacecraft 
4 Maneuvers
Convergence (1e-6) = 226 generations
Tot Dv spacecraft 1 = 5.3532623146243346 [m/s]
Tot Dv spacecraft 2 = 2.6134250206001215 [m/s]
Tot Dv spacecraft 3 = 4.057814328660423 [m/s]
Tot Dv spacecraft 4 = 5.2607626069270434 [m/s]

[Spacecraft_1_2_side_view_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593517/Spacecraft_1_2_side_view_trajectory_plot.pdf)
[Spacecraft_1_2_top_view_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593518/Spacecraft_1_2_top_view_trajectory_plot.pdf)
[Spacecraft_1_2_body_fixed_frame_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593519/Spacecraft_1_2_body_fixed_frame_trajectory_plot.pdf)
[Spacecraft_3_4_side_view_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593520/Spacecraft_3_4_side_view_trajectory_plot.pdf)
[Spacecraft_3_4_top_view_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593521/Spacecraft_3_4_top_view_trajectory_plot.pdf)
[Spacecraft_3_4_body_fixed_frame_trajectory_plot.pdf](https://github.com/rasmusmarak/TOSS/files/11593522/Spacecraft_3_4_body_fixed_frame_trajectory_plot.pdf)
[case_2_fitness_over_generations.pdf](https://github.com/rasmusmarak/TOSS/files/11593523/case_2_fitness_over_generations.pdf)
[case_2_coverage_over_time.pdf](https://github.com/rasmusmarak/TOSS/files/11593524/case_2_coverage_over_time.pdf)
[case_2_distance_deviation_over_time.pdf](https://github.com/rasmusmarak/TOSS/files/11593525/case_2_distance_deviation_over_time.pdf)

**Comment by rasmusmarak** [comment]
**Additional tests:**

3 Spacecraft 
2 maneuvers

Spacecraft 0 tot dv  0.6795063578765187
Spacecraft 1 tot dv  1.3500464175989317
Spacecraft 2 tot dv  0.5299005465327239

![Skärmavbild 2023-06-02 kl  09 50 36](https://github.com/rasmusmarak/TOSS/assets/60341145/1361323c-b558-45eb-ab86-1aa33a6bc17e)
![Skärmavbild 2023-06-02 kl  09 51 32](https://github.com/rasmusmarak/TOSS/assets/60341145/29797148-0808-4013-b819-2522beb07af0)
![Skärmavbild 2023-06-02 kl  10 31 21](https://github.com/rasmusmarak/TOSS/assets/60341145/a00ac17f-0978-42c7-821b-affc715f0986)

**Comment by rasmusmarak** [comment]
**Additional tests:**

4 Spacecraft 
2 maneuvers

covered space = 0.4449151325230582

Spacecraft 0 tot dv  1.8933243134012598
Spacecraft 1 tot dv  0.18647151452013866
Spacecraft 2 tot dv  0.5027391121661303
Spacecraft 3 tot dv  1.5101085748592995

![Skärmavbild 2023-06-02 kl  10 36 55](https://github.com/rasmusmarak/TOSS/assets/60341145/76b3ce5c-aaba-4a9c-874a-06e4fc7bbfa9)
![Skärmavbild 2023-06-02 kl  10 37 42](https://github.com/rasmusmarak/TOSS/assets/60341145/df7d036d-aabf-4e65-aef3-975f47c961c5)
![Skärmavbild 2023-06-02 kl  10 38 18](https://github.com/rasmusmarak/TOSS/assets/60341145/ec0990d0-770e-4f35-af5d-4b79c3dc8ad1)
![Skärmavbild 2023-06-02 kl  10 38 42](https://github.com/rasmusmarak/TOSS/assets/60341145/8a1e172b-dd91-4001-acf8-8eeecd8f6844)

**Comment by rasmusmarak** [comment]
**Additional tests**

2 Spacecraft 
4 Maneuvers

covered space = 0.383649614922649

Spacecraft 0 tot dv  5.513748286137223
Spacecraft 1 tot dv  1.2225808011534423


![Skärmavbild 2023-06-02 kl  10 42 38](https://github.com/rasmusmarak/TOSS/assets/60341145/cae66850-62d7-4880-8c0d-721407e2a8be)
![Skärmavbild 2023-06-02 kl  10 43 30](https://github.com/rasmusmarak/TOSS/assets/60341145/ea8b5c1a-61ee-4ef1-a045-29dba22dfa5e)
![Skärmavbild 2023-06-02 kl  10 44 06](https://github.com/rasmusmarak/TOSS/assets/60341145/67b190b2-789f-4a04-bafe-74a1bac4c51a)
![Skärmavbild 2023-06-02 kl  10 44 39](https://github.com/rasmusmarak/TOSS/assets/60341145/5eafea9f-ba7c-4e1d-8389-02ccd753f51d)

**Comment by rasmusmarak** [comment]
**Additional tests**

3 Spacecraft
4 maneuvers

Covered space = 0.2917844752563947

Spacecraft 0 tot dv  2.877462729891747
Spacecraft 1 tot dv  1.2180622349402332
Spacecraft 2 tot dv  2.5889929105668585

![Skärmavbild 2023-06-02 kl  10 47 35](https://github.com/rasmusmarak/TOSS/assets/60341145/c58d3f49-5e95-4c0e-a6a0-6fac2f7c7f1a)
![Skärmavbild 2023-06-02 kl  10 48 13](https://github.com/rasmusmarak/TOSS/assets/60341145/be93ad47-ca69-4860-8359-0c7bf3809c68)
![Skärmavbild 2023-06-02 kl  10 48 45](https://github.com/rasmusmarak/TOSS/assets/60341145/14645c17-46a4-4bfd-b743-a327ae86e536)
![Skärmavbild 2023-06-02 kl  10 49 31](https://github.com/rasmusmarak/TOSS/assets/60341145/ab10e305-62ae-42dc-b01f-490931456d32)
