### ISSUE TITLE
Profile code 

### ISSUE THREAD

**Issue by gomezzz** [rasmusmarak/TOSS#29]
Please post some cprofile outputs to see where our runtime is going, it is starting to be quite slow :pray:

**Comment by rasmusmarak** [comment]
**Test 1:**

_Search space:_   Cartesian coordinates [r_x,r_y,r_z,v_x,v_y,v_z]
- lower_bound = [-6000,-6000,-6000,0,0,0]
- upper_bound = [6000,6000,6000,2.5,2.5,2.5]

_Integration time:_
- t0 = 0
- tf = 20*3600 (i.e 20h)

_Problem parameters:_
- body density = 533
- body mu = 665.666

_Algorithm parameters:_
- initial step =  600 [seconds]
- integration algorithm = DP8713M   (using Desolver)
- population size = 10
- number of evolutions = 32
- optimization algorithm = SADE (self-adaptive differential evolution, using pygmo)


_**Results:**_
- Algorithm run time = 38min 9.2s 
- champion fitness value = 1599897.43729276
- champion chromosome = [ 3.54273804e+03, -2.05937976e+03, -2.90055903e+03,  3.45286575e-01, 4.45044180e-01, 1.43148382e-01]
- F = 0.259343
- CR = 0.626794
- dx = 8507.09
- df = 1.06143e+08


**Trajectory with mesh:**
<img width="433" alt="Skärmavbild 2023-03-05 kl  18 27 09" src="https://user-images.githubusercontent.com/60341145/222976007-552277c6-8dc9-4b7a-bab5-e8604b556b4f.png">

**Trajectory (x and y axis):**
<img width="687" alt="Skärmavbild 2023-03-05 kl  18 27 32" src="https://user-images.githubusercontent.com/60341145/222976033-32a46e60-6a37-4fa2-abd1-7c2223b8eed5.png">

**C-profile: **
_Sorted by number of calls:_ [output_calls.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892424/output_calls.txt)
_Sorted by time:_ [output_time.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892429/output_time.txt)

**Comment by rasmusmarak** [comment]
**Test 2:**

_Search space:_   Osculating orbital elements [a, e, o, w, i, ea]
- lower_bound = [5000, 0, 0, 0, 0, 0]
- upper_bound = [5000, 1, 2*pi, 2*pi, pi, 2*pi]

_Integration time:_
- t0 = 0
- tf = 20*3600 (i.e 20h)

_Problem parameters:_
- body density = 533
- body mu = 665.666

_Algorithm parameters:_
- initial step =  600 [seconds]
- integration algorithm = DP8713M   (using Desolver)
- population size = 10
- number of evolutions = 32
- optimization algorithm = SADE (self-adaptive differential evolution, using pygmo)


_**Results:**_
- Algorithm run time = 57min 40.5s 
- champion integration time = 7.2s
- champion fitness value = 11824891.30506848
- champion chromosome = [1.11372603e+04, 4.68773238e-01, 2.20821729e+00, 4.51629780e-01, 3.33853297e+00, 3.48571918e-01]
- F = 0.774538
- CR = 0.26791
- dx = 2724.48
- df = 3.53187e+06


**Trajectory with mesh:**
<img width="442" alt="Skärmavbild 2023-03-05 kl  19 40 19" src="https://user-images.githubusercontent.com/60341145/222979382-d862ef28-b67f-4244-87e9-f27bc1244f73.png">

**Trajectory (x and y axis):**
<img width="689" alt="Skärmavbild 2023-03-05 kl  19 40 53" src="https://user-images.githubusercontent.com/60341145/222979407-370af0c1-358c-4fec-a03f-6600d7f407d9.png">


**C-profile: **
_Sorted by number of calls:_  [output_calls.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892641/output_calls.txt)
_Sorted by time:_  [output_time.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892644/output_time.txt)

**Comment by rasmusmarak** [comment]
**Test 3:**

_Search space:_   Osculating orbital elements [a, e, o, w, i, ea]
- lower_bound = [5000, 0, 0, 0, 0, 0]
- upper_bound = [5000, 1, 2*pi, 2*pi, pi, 2*pi]

_Integration time:_
- t0 = 0
- tf = 20*3600 (i.e 20h)

_Problem parameters:_
- body density = 533
- body mu = 665.666
- target altitude = 5000 [m]
- radius bounding sphere = 3500 [m]
- collision penalty = 1e30

_Algorithm parameters:_
- initial step =  600 [seconds]
- integration algorithm = DP8713M   (using Desolver)
- population size = 10
- number of evolutions = 32
- optimization algorithm = SADE (self-adaptive differential evolution, using pygmo)


_**Results:**_
- Algorithm run time = 35min 53.4s 
- champion integration time = 4.4s
- champion fitness value = 10030080.69184285
- champion chromosome = [1.02346115e+04, 5.04262474e-01, 1.40521347e+00, 3.03148072e+00, 2.68878957e-01, 5.74690265e+00]
- F = 0.405411
- CR = 0.752927
- dx = 3445.18
- df = 2.10126e+07


**Trajectory with mesh:**
<img width="453" alt="Skärmavbild 2023-03-05 kl  20 54 30" src="https://user-images.githubusercontent.com/60341145/222982615-dc9ee270-9915-4651-8ef6-ff44503e6422.png">

**Trajectory (x and y axis):**
<img width="534" alt="Skärmavbild 2023-03-05 kl  20 54 52" src="https://user-images.githubusercontent.com/60341145/222982628-ec9fd135-759f-44f4-a22c-d829dfe40a4f.png">

**C-profile: **
_Sorted by number of calls:_  [output_calls.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892810/output_calls.txt)
_Sorted by time:_  [output_time.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892812/output_time.txt)

**Comment by rasmusmarak** [comment]
**Test 3:**

**Basic problem:**
- changed to osculating orbital elements
- added collision detection
- added rotation of satellite position using quaternions

_Search space:_   Osculating orbital elements [a, e, o, w, i, ea]
- lower_bound = [5000, 0, 0, 0, 0, 0]
- upper_bound = [5000, 1, 2*pi, 2*pi, pi, 2*pi]

_Integration time:_
- t0 = 0
- tf = 20*3600 (i.e 20h)

_Problem parameters:_
- body density = 533
- body mu = 665.666
- target altitude = 5000 [m]
- radius bounding sphere = 3500 [m]
- collision penalty = 1e30
- spin axis declination = 64 [degrees]
- spin axis right ascension = 69 [degrees]
- spin period = 12.06*3600 [seconds] (i.e 12.06h)

_Algorithm parameters:_
- initial step =  600 [seconds]
- integration algorithm = DP8713M   (using Desolver)
- population size = 10
- number of evolutions = 32
- optimization algorithm = SADE (self-adaptive differential evolution, using pygmo)


_**Results:**_
- Algorithm run time = 15min 35.9s 
- champion integration time = 3.5s
- champion fitness value = 20938771.53471591
- champion chromosome = [9.72752753e+03, 3.64128116e-02, 1.28319173e+00, 1.69622584e+00, 2.18503270e+00, 2.66184179e+00]
- F = 0.763792
- CR = 0.686998
- dx = 1606.6
- df = 6.64294e+07


**Trajectory with mesh:**
<img width="534" alt="Skärmavbild 2023-03-05 kl  21 56 53" src="https://user-images.githubusercontent.com/60341145/222985526-9dda33e9-9722-47a6-8b04-2b5d5d92991c.png">

**Trajectory (x and y axis):**
<img width="694" alt="Skärmavbild 2023-03-05 kl  21 57 15" src="https://user-images.githubusercontent.com/60341145/222985540-f2654a29-85d1-46b7-8022-02efe2dd3029.png">

**C-profile: **
_Sorted by number of calls:_  [output_calls.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892942/output_calls.txt)
_Sorted by time:_  [output_time.txt](https://github.com/rasmusmarak/67P-Swarm/files/10892944/output_time.txt)

**Comment by gomezzz** [comment]
In future plots ideally add fitness over generations

**Comment by rasmusmarak** [comment]
**Profile code:**

_Number of spacecrafts_ = 1
_Number of maneuvers_ = 1
_Mission time_ = 2419200 [s] (ie 4 weeks, or 28 days)

_Population size_ = 120
_Number of generations_ = 10
_Number of threads_ = 40

_Penalty scaling factor_ = 0.1
_Max velocity scaling factor_ = 40

_Radius bounding spheres_ = [4000, 15000]. (i.e inner and outer)
_Rotation of body_ = True



[output_calls.txt](https://github.com/rasmusmarak/TOSS/files/11407390/output_calls.txt)
[output_time.txt](https://github.com/rasmusmarak/TOSS/files/11407391/output_time.txt)
