### ISSUE TITLE
Look into performance aspects

### ISSUE THREAD

**Issue by gomezzz** [rasmusmarak/TOSS#31]
- Think about fitness #7 to see if could do parallel 
- Look into how long we need to run to get convergence

**Comment by rasmusmarak** [comment]
_**Tests on MacBook Pro (2018, Intel i7, 6-core 2,6 GHz)**_

Strong scale:
_Number of generations:_ 10
_Core count:_ [1, 2, 4, 8]
_Population count:_ [80, 40, 20, 10]

![Skärmavbild 2023-03-28 kl  09 29 35](https://user-images.githubusercontent.com/60341145/228161312-e04355ed-a4ac-4b74-997a-e08eaaa76c6c.png)

![Skärmavbild 2023-03-28 kl  09 34 49](https://user-images.githubusercontent.com/60341145/228162513-7603a6f7-ffd7-48c6-ad7d-de0538ae2b3b.png)


--------------------------------------------------------------------

Weak scale:
_Number of generations:_ 32
_Core count:_ [1, 2, 4, 8]
_Population count:_ [10, 10, 10, 10]

![Skärmavbild 2023-03-28 kl  09 35 37](https://user-images.githubusercontent.com/60341145/228162670-5b6f0f1e-c297-40c7-a1d5-07e06d2677f2.png)

![Skärmavbild 2023-03-28 kl  09 36 33](https://user-images.githubusercontent.com/60341145/228162957-6fc5e5b1-98e5-4520-964a-8e870e396879.png)

**Comment by rasmusmarak** [comment]
_**Tests on Emma (without multiprocessing for initialization)**_

**Strong scale:**
_Number of generations:_ 10
_Core count:_ [1, 2, 4, 8]
_Population count:_ [80, 40, 20, 10]

![Skärmavbild 2023-03-28 kl  09 50 19](https://user-images.githubusercontent.com/60341145/228166387-aa4f6130-61d9-4414-91b9-f4ba23e0cda6.png)

**Comment by rasmusmarak** [comment]
#36 For updated performance tests.
