### ISSUE TITLE
Find a good fitness function 

### ISSUE THREAD

**Issue by gomezzz** [rasmusmarak/TOSS#7]
We need to set up one that describes our optimization goals better.

Can include things like
- Proximity
- Propellant use 
- View angles on 67P
- ...

**Comment by rasmusmarak** [comment]
Current fitness function capabilities:
- Target-altitude (will likely not be used)
- Far-distance penalty
- Close-distance penalty
- Single spacecraft space coverage (should be improved)
- Cumulative spacecraft space coverage (needs update)

Things to add to fitness function:
- Outside in-line-of-sight penalty (using Möller-trumbore)
- Propellant usage
- Solar Radiation Pressure
- Proximity of spacecrafts 
- View angles on 67P
